import { Experience } from './experienceClass';

export const EXPERIENCE: Experience[] = [
  {
    title: 'Web Design, Sytem Development, Consultant',
    company: 'Self Employed',
    location: 'Denver, Colorado',
    startDate: new Date('July, 2018').toString(),
    endDate: new Date().toString(),
    comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque sit amet magna id accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a porttitor orci. Proin et quam sit amet purus viverra rutrum. In sed risus sem. Nullam molestie dui libero, quis ultrices quam gravida id. Fusce vel ex hendrerit, vehicula felis id, sollicitudin nisl. In consequat, tellus sagittis lobortis ultrices, dui est faucibus erat, et venenatis velit orci et ante. Integer fringilla mi eget turpis finibus, quis gravida ligula auctor. Donec justo diam, blandit ultrices semper et, sollicitudin ac odio. Praesent ultrices varius lorem, nec convallis velit fermentum nec. Maecenas vel libero tincidunt, eleifend enim non, lacinia odio. Aliquam rutrum at risus ut molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean finibus faucibus efficitur. Nullam at ligula varius, sollicitudin risus vel, porttitor lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sollicitudin, mauris et vulputate posuere, ante metus tincidunt purus, at facilisis purus tortor eu velit. Vivamus sollicitudin tristique commodo. Vivamus rutrum nisi sed molestie malesuada. Quisque sed dictum dolor. Curabitur rutrum rhoncus urna, nec auctor nulla bibendum vitae. Mauris pretium nec leo eget pretium. Phasellus ut justo in erat pharetra egestas. Nulla vehicula dictum fringilla. Sed nec molestie elit, in hendrerit mauris. Praesent ultrices eleifend volutpat. Integer sit amet velit ut nisl ultricies pellentesque. Sed sit amet est interdum, rhoncus elit quis, suscipit enim. Vivamus ante sapien, fermentum quis eros sed, hendrerit bibendum velit. Suspendisse sit amet congue tortor. Nam lobortis tincidunt orci nec hendrerit. Quisque gravida rhoncus felis id ullamcorper. Nullam eget posuere metus. Aliquam convallis ac odio vitae porttitor. Nullam finibus molestie augue, non sodales nulla feugiat et. Vestibulum ut ante sit amet turpis viverra porttitor in non nisi. Nullam gravida quam ut sapien hendrerit, at lobortis eros hendrerit. Mauris mattis, metus eu suscipit fringilla, odio enim vehicula neque, sit amet vestibulum purus nibh at mauris. Nunc id dolor vitae diam vestibulum fermentum. Phasellus fringilla quis lorem at feugiat. Vivamus cursus cursus magna, at semper dolor. Praesent aliquet pretium pharetra. Quisque laoreet rhoncus faucibus. Nunc vulputate, est sit amet bibendum rutrum, risus metus rutrum eros, nec hendrerit felis libero ut mauris. Donec auctor pulvinar massa sit amet aliquam. Maecenas ornare libero euismod urna condimentum placerat. Integer vitae leo eget nibh dapibus eleifend non vel lorem. Aenean finibus orci a lacus porttitor maximus. Praesent varius placerat dolor congue dapibus. In nec urna eget tellus feugiat tempor. Quisque ut massa condimentum metus venenatis volutpat. Aenean ',
    description: [
      'Working on local business websites and in house systems for a variety of companies.  Mainly working with Angular/cli, MongoDB, Node.js, and Express.js, as well as WordPress.',
      'Auditing IT infrastructure for local companies and recommending improvements for their IT models.'
    ]
  },
  {
    title: 'IT Manager',
    company: 'AJS Holdings LLC',
    location: 'Denver, Colorado',
    startDate: new Date('December, 2017').toString(),
    endDate: new Date('July, 2018').toString(),
    comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque sit amet magna id accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a porttitor orci. Proin et quam sit amet purus viverra rutrum. In sed risus sem. Nullam molestie dui libero, quis ultrices quam gravida id. Fusce vel ex hendrerit, vehicula felis id, sollicitudin nisl. In consequat, tellus sagittis lobortis ultrices, dui est faucibus erat, et venenatis velit orci et ante. Integer fringilla mi eget turpis finibus, quis gravida ligula auctor. Donec justo diam, blandit ultrices semper et, sollicitudin ac odio. Praesent ultrices varius lorem, nec convallis velit fermentum nec. Maecenas vel libero tincidunt, eleifend enim non, lacinia odio. Aliquam rutrum at risus ut molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean finibus faucibus efficitur. Nullam at ligula varius, sollicitudin risus vel, porttitor lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sollicitudin, mauris et vulputate posuere, ante metus tincidunt purus, at facilisis purus tortor eu velit. Vivamus sollicitudin tristique commodo. Vivamus rutrum nisi sed molestie malesuada. Quisque sed dictum dolor. Curabitur rutrum rhoncus urna, nec auctor nulla bibendum vitae. Mauris pretium nec leo eget pretium. Phasellus ut justo in erat pharetra egestas. Nulla vehicula dictum fringilla. Sed nec molestie elit, in hendrerit mauris. Praesent ultrices eleifend volutpat. Integer sit amet velit ut nisl ultricies pellentesque. Sed sit amet est interdum, rhoncus elit quis, suscipit enim. Vivamus ante sapien, fermentum quis eros sed, hendrerit bibendum velit. Suspendisse sit amet congue tortor. Nam lobortis tincidunt orci nec hendrerit. Quisque gravida rhoncus felis id ullamcorper. Nullam eget posuere metus. Aliquam convallis ac odio vitae porttitor. Nullam finibus molestie augue, non sodales nulla feugiat et. Vestibulum ut ante sit amet turpis viverra porttitor in non nisi. Nullam gravida quam ut sapien hendrerit, at lobortis eros hendrerit. Mauris mattis, metus eu suscipit fringilla, odio enim vehicula neque, sit amet vestibulum purus nibh at mauris. Nunc id dolor vitae diam vestibulum fermentum. Phasellus fringilla quis lorem at feugiat. Vivamus cursus cursus magna, at semper dolor. Praesent aliquet pretium pharetra. Quisque laoreet rhoncus faucibus. Nunc vulputate, est sit amet bibendum rutrum, risus metus rutrum eros, nec hendrerit felis libero ut mauris. Donec auctor pulvinar massa sit amet aliquam. Maecenas ornare libero euismod urna condimentum placerat. Integer vitae leo eget nibh dapibus eleifend non vel lorem. Aenean finibus orci a lacus porttitor maximus. Praesent varius placerat dolor congue dapibus. In nec urna eget tellus feugiat tempor. Quisque ut massa condimentum metus venenatis volutpat. Aenean ',
    description: [
      'Maintain hardware inventory and supplies while working closely with accounting to stay on, usually under, budget.',
      'Implement software and hardware update and maintenance schedules.',
      'Assign duties, responsibilities, and projects to the IT team, while providing training and mentorship.',
      'Oversee technical installation of equipment for five warehouses and ten storefronts.',
      'Meet regularly with owners, investors,  and the Board of Directors to plan strategic direction for the company.',
      'Planned the IT infrastructure for four new stores and two warehouses.'
    ]
  },
  {
    title: 'IT Supervisor',
    company: 'AJS Holdings LLC',
    location: 'Denver, Colorado',
    startDate: new Date('September, 2016').toString(),
    endDate: new Date('December, 2017').toString(),
    comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque sit amet magna id accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a porttitor orci. Proin et quam sit amet purus viverra rutrum. In sed risus sem. Nullam molestie dui libero, quis ultrices quam gravida id. Fusce vel ex hendrerit, vehicula felis id, sollicitudin nisl. In consequat, tellus sagittis lobortis ultrices, dui est faucibus erat, et venenatis velit orci et ante. Integer fringilla mi eget turpis finibus, quis gravida ligula auctor. Donec justo diam, blandit ultrices semper et, sollicitudin ac odio. Praesent ultrices varius lorem, nec convallis velit fermentum nec. Maecenas vel libero tincidunt, eleifend enim non, lacinia odio. Aliquam rutrum at risus ut molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean finibus faucibus efficitur. Nullam at ligula varius, sollicitudin risus vel, porttitor lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sollicitudin, mauris et vulputate posuere, ante metus tincidunt purus, at facilisis purus tortor eu velit. Vivamus sollicitudin tristique commodo. Vivamus rutrum nisi sed molestie malesuada. Quisque sed dictum dolor. Curabitur rutrum rhoncus urna, nec auctor nulla bibendum vitae. Mauris pretium nec leo eget pretium. Phasellus ut justo in erat pharetra egestas. Nulla vehicula dictum fringilla. Sed nec molestie elit, in hendrerit mauris. Praesent ultrices eleifend volutpat. Integer sit amet velit ut nisl ultricies pellentesque. Sed sit amet est interdum, rhoncus elit quis, suscipit enim. Vivamus ante sapien, fermentum quis eros sed, hendrerit bibendum velit. Suspendisse sit amet congue tortor. Nam lobortis tincidunt orci nec hendrerit. Quisque gravida rhoncus felis id ullamcorper. Nullam eget posuere metus. Aliquam convallis ac odio vitae porttitor. Nullam finibus molestie augue, non sodales nulla feugiat et. Vestibulum ut ante sit amet turpis viverra porttitor in non nisi. Nullam gravida quam ut sapien hendrerit, at lobortis eros hendrerit. Mauris mattis, metus eu suscipit fringilla, odio enim vehicula neque, sit amet vestibulum purus nibh at mauris. Nunc id dolor vitae diam vestibulum fermentum. Phasellus fringilla quis lorem at feugiat. Vivamus cursus cursus magna, at semper dolor. Praesent aliquet pretium pharetra. Quisque laoreet rhoncus faucibus. Nunc vulputate, est sit amet bibendum rutrum, risus metus rutrum eros, nec hendrerit felis libero ut mauris. Donec auctor pulvinar massa sit amet aliquam. Maecenas ornare libero euismod urna condimentum placerat. Integer vitae leo eget nibh dapibus eleifend non vel lorem. Aenean finibus orci a lacus porttitor maximus. Praesent varius placerat dolor congue dapibus. In nec urna eget tellus feugiat tempor. Quisque ut massa condimentum metus venenatis volutpat. Aenean ',
    description: [
      'Manage deployment and support of internal infrastructure system ensuring that periodic tasks are completed by each team member.',
      'Oversee projects to design and implement local IT infrastructure, POS terminals, network systems, and servers.',
      'Assign schedules, coordinate staff and allocate resources to ensure efficiency and productivity are maximized.',
      'Manage G-suite policies and services for a medium sized business.',
      'Train end users on correct use of equipment and software.'
    ]
  },
  {
    title: 'IT Administrator',
    company: 'AJS Holdings LLC',
    location: 'Denver, Colorado',
    startDate: new Date('January, 2016').toString(),
    endDate: new Date('September, 2016').toString(),
    comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque sit amet magna id accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a porttitor orci. Proin et quam sit amet purus viverra rutrum. In sed risus sem. Nullam molestie dui libero, quis ultrices quam gravida id. Fusce vel ex hendrerit, vehicula felis id, sollicitudin nisl. In consequat, tellus sagittis lobortis ultrices, dui est faucibus erat, et venenatis velit orci et ante. Integer fringilla mi eget turpis finibus, quis gravida ligula auctor. Donec justo diam, blandit ultrices semper et, sollicitudin ac odio. Praesent ultrices varius lorem, nec convallis velit fermentum nec. Maecenas vel libero tincidunt, eleifend enim non, lacinia odio. Aliquam rutrum at risus ut molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean finibus faucibus efficitur. Nullam at ligula varius, sollicitudin risus vel, porttitor lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sollicitudin, mauris et vulputate posuere, ante metus tincidunt purus, at facilisis purus tortor eu velit. Vivamus sollicitudin tristique commodo. Vivamus rutrum nisi sed molestie malesuada. Quisque sed dictum dolor. Curabitur rutrum rhoncus urna, nec auctor nulla bibendum vitae. Mauris pretium nec leo eget pretium. Phasellus ut justo in erat pharetra egestas. Nulla vehicula dictum fringilla. Sed nec molestie elit, in hendrerit mauris. Praesent ultrices eleifend volutpat. Integer sit amet velit ut nisl ultricies pellentesque. Sed sit amet est interdum, rhoncus elit quis, suscipit enim. Vivamus ante sapien, fermentum quis eros sed, hendrerit bibendum velit. Suspendisse sit amet congue tortor. Nam lobortis tincidunt orci nec hendrerit. Quisque gravida rhoncus felis id ullamcorper. Nullam eget posuere metus. Aliquam convallis ac odio vitae porttitor. Nullam finibus molestie augue, non sodales nulla feugiat et. Vestibulum ut ante sit amet turpis viverra porttitor in non nisi. Nullam gravida quam ut sapien hendrerit, at lobortis eros hendrerit. Mauris mattis, metus eu suscipit fringilla, odio enim vehicula neque, sit amet vestibulum purus nibh at mauris. Nunc id dolor vitae diam vestibulum fermentum. Phasellus fringilla quis lorem at feugiat. Vivamus cursus cursus magna, at semper dolor. Praesent aliquet pretium pharetra. Quisque laoreet rhoncus faucibus. Nunc vulputate, est sit amet bibendum rutrum, risus metus rutrum eros, nec hendrerit felis libero ut mauris. Donec auctor pulvinar massa sit amet aliquam. Maecenas ornare libero euismod urna condimentum placerat. Integer vitae leo eget nibh dapibus eleifend non vel lorem. Aenean finibus orci a lacus porttitor maximus. Praesent varius placerat dolor congue dapibus. In nec urna eget tellus feugiat tempor. Quisque ut massa condimentum metus venenatis volutpat. Aenean ',
    description: [
      'Provide technical support to over three hundred employees on site, through phone, and via remote desktop.',
      'Maintain, upgrade, and troubleshoot network equipment, P.O.S. terminals, security systems, and office hardware.',
      'Monitor security systems and remote security servers for five warehouses and ten storefronts.',
    ]
  }
];
